### ISSUE TITLE
Mangling for Clang's matrix type extension

### ISSUE THREAD

**Issue by fhahn** [itanium-cxx-abi/cxx-abi#100]
We would like to add support for mangling Clang's matrix types (see https://clang.llvm.org/docs/MatrixTypes.html#matrixtypes). A matrix type consists of 3 components: the element type, an expression for the number of rows and an expression for the number of columns. Each component can be a template argument.

@rjmccall suggested the following options to use a vendor-extended qualifier/type:
 

> we could either treat the entire matrix type as a vendor-extended qualifier on the element type (i.e. U11matrix_typeILi3ELi4EEi), or we could extend the vendor-extended type mangling to allow template-args (i.e. u11matrix_typeIiLi3ELi4EE). The latter is probably better and should fit cleanly into the mangling grammar.

**Comment by rjmccall** [comment]
Right.  I think the right adjustment here would be to just directly model parameterized vendor-extension types in the grammar analogously to how we model parameterized vendor-extension qualifiers:

```
<builtin-type> ::= u <source-name> [<template-args>]
```

It's possible to model this (grammatically) as a qualifier, but that creates two problems:
- The vendor extension may not have a meaningful "unqualified type".  That's not a problem for Florian's matrix types, but it would be a problem for e.g. an arbitrary-size integer type or something similar.
- Only fully-qualified and unqualified types are substitution candidates, not any sets in between.  This creates substantial implementation difficulties when mangling qualified extended types, as e.g. the type `const vector(4) int` would have to create substitution candidates for the full type and `int` (if that were substitutable) but not `vector(4) int`.  It also means the vendor extension will have to be spelled out again if it's repeated without the standard qualifier elsewhere in the mangling.

**Comment by rjmccall** [comment]
Okay, I think this has be open for comment long enough.
