### ISSUE TITLE
Mangling for vendor-specific expressions

### ISSUE THREAD

**Issue by jyknight** [itanium-cxx-abi/cxx-abi#112]
I'm forking this ABI proposal off from https://gcc.gnu.org/PR88115 -- but see that for more context as to why this proposal is important.

Both GCC and Clang implement a number of vendor-specific expressions which do not act like a function call. Some examples are `__builtin_convertvector(src_expression, destination_type)`, `__builtin_offsetof(type, field)`, and `__alignof__(type or expression)` (which, note, has different semantics than standard alignof). Finally, there's `__typeof__(type or expression)` which "returns" a type, not a value. 

A long long time ago, https://gcc.gnu.org/PR13740 and https://gcc.gnu.org/PR11078 discussed a variety of possible mangling syntax extensions for this sort of thing. The most promising, AFAICT, was `Y <source-name> <template-arg>+ E`.

Unfortunately, none of the suggestions were implemented, so there is currently no vendor extensibility for expressions, other than via a vendor-specific "operator", `<operator-name> ::= v <digit> <source-name>`. This cannot be used for the above kinds of expressions, because it allows only expressions as arguments, not types. Additionally, it seems to be intended for vendor _overloadable_ operators -- which these are not.

Recently, however, the vendor-extended type syntax did get template args, so we _do_ now have syntax to mangle vendor-specific type. `__typeof__(T)` could be mangled as `u10__typeof__IT_E`.

Therefore, for consistency, instead of adopting one of the previous proposals using "Y", I'd like to propose adding the same "u" syntax to expression context:
`<expression> ::= u <source-name> [<template-args>] # vendor extended expression`

Some examples:
`__alignof__(T)` -> `u11__alignof__IT_E`
`__alignof__(T{})` -> `u11__alignof__IXtlT_E`
`__builtin_offsetof(T, foo)` -> `u18__builtin_offsetofIT_3fooE`

**Comment by rjmccall** [comment]
SGTM.  Mind opening a PR?  We'll leave it open for a couple weeks for comment.

**Comment by jyknight** [comment]
I'm having second thoughts about the syntax proposed above:
  `<expression> ::= u <source-name> [<template-args>] # vendor extended expression`
Another option, which I'm now thinking may be preferable, would be:
  `<expression> ::= u <source-name> <template-arg>* E # vendor extended expression`

The effective difference between the two is that in the latter, there is no "I" introducing the args, and there is an "E" even with no args.

While the former is the same as for 'u' in `<type>`, the latter seems more like existing expressions. E.g.:
  `<expression> ::= sP <template-arg>* E # sizeof...(T), size of a captured template parameter pack from an alias template`

Opinions on which way to go?
