### ISSUE TITLE
Link to cxx-abi-dev archives broken

### ISSUE THREAD

**Issue by tahina-pro** [itanium-cxx-abi/cxx-abi#116]
The link to the cxx-abi-dev mailing list archives is broken as of 2021-01-11:

https://github.com/itanium-cxx-abi/cxx-abi/blob/b359d28971bdb961dd9b61bd0ef8c884452b4740/index.html#L42

I couldn't find the new official place, if any. If so, then could anybody please update the link here?

If not, then are there any plans to reinstate those archives anyhow? FYI, I found an unofficial copy at https://cxx-abi-dev.codesourcery.narkive.com/  but I would fully understand that the C++ ABI draft should not point to it.

Thank you in advance,

**Comment by rjmccall** [comment]
Sorry, I'd been meaning to get to this.  I've added the raw pipermail archives to the repository and updated the link in #117.

**Comment by rjmccall** [comment]
Sorry, I'd been meaning to get to this.  I've added the raw pipermail archives to the repository and updated the link in
