### ISSUE TITLE
What is the intended use of the Array Construction and Destruction API?

### ISSUE THREAD

**Issue by chgalante** [itanium-cxx-abi/cxx-abi#133]
Section 3.3.4 of the ABI (Array Construction and Destruction API) states that:
`An ABI-compliant system shall provide several runtime routines for use in array construction and destruction. They may be used by compilers, but their use is not required. `

For a bare-metal C++ application that does not include the C++ STL (-nostdlib), assuming we are using a gcc compiler which is ABI-compliant, would it be possible to exercise the functions in the Array Construction and Destruction API? If it is possible, in what scenario is it possible?

In general, I am confused by what these functions are used for. If anybody can explain this to me, I would appreciate that greatly!

Thank you in advance!

**Comment by jwakely** [comment]
Programs are not supposed to exercise them. They exist for the compiler to call when the code contains a `new X[n]` expression.

**Comment by chgalante** [comment]
Thank you for the quick reply!

What is the difference between these "__cxa_vec_*" functions and defining the new[] or delete[] operators?

**Comment by rjmccall** [comment]
`__cxa_vec_new` also constructs the array elements, whereas an `operator new` function just allocates memory.

**Comment by jwakely** [comment]
But more generally, these `__cxa_vec` functions are the implementation details for the C++ language itself.

Programs should not be calling them. You should be use `new X[n]` to allocate arrays of objects, and the compiler will do whatever it needs to do to make that work. That might involve calling these functions (or it might not, if the compiler chooses to do it differently).

If you think you want to use these functions, you're almost certainly wrong.

**Comment by chgalante** [comment]
Thanks for the replies,

I am not trying to use the functions in the program. Currently I've only implemented the new and new[] operators. Up until now, I had thought that this was enough as the new[] operator is constructing the objects in the array properly. 

After writing more code, I've had to implement other functions such as __cxa_pure_virtual, __cxa_guard_acquire and __cxa_guard_release because I was receiving an error when compiling saying that these references were undefined. It was clear to me, for these ones, why these functions had to be defined. 

I am worried, though, that by not implementing the cxa_vec_* functions I will run into a similar situation, whereby the compiler tries to link to one of those cxa_vec_* functions and I am missing the implementation. I would prefer to only implement the bare minimum set of these functions and leave ones that are not exercised by the compiler unimplemented.

If the compiler has not called these so far, is it safe to assume they will not be called?

**Comment by rjmccall** [comment]
Safe, as in absolutely guaranteed, even if you install a new compiler?  No; the ABI says they're supposed to be there, so compilers are allowed to use them however they please.  But a specific compiler version with specific compiler flags is likely to either use or not use the functions fairly consistently over time, so you aren't likely to be suddenly surprised by a new use, so there's not much harm in writing them reactively.

With that said, both of the major C++ standard library implementations have actually extracted out a common ABI library that you can use without introducing a dependency on the entire library.  I'd be a little surprised if you can't find something that meets your needs between `libsupc++` (GNU) and `libc++abi` (LLVM).

**Comment by jwakely** [comment]
> After writing more code, I've had to implement other functions such as __cxa_pure_virtual, __cxa_guard_acquire and __cxa_guard_release because I was receiving an error when compiling saying that these references were undefined. It was clear to me, for these ones, why these functions had to be defined.

If you're using GCC, you should be able to link with `-lsupc++` (even on bare metal) to get definitions of those. I think you're doing something wrong.

**Comment by chgalante** [comment]
> Safe, as in absolutely guaranteed, even if you install a new compiler? No; the ABI says they're supposed to be there, so compilers are allowed to use them however they please. But a specific compiler version with specific compiler flags is likely to either use or not use the functions consistently, so you aren't likely to be suddenly surprised by a new use, which means there's not much harm in putting off writing them until you have a concrete need.

This is reassuring, thanks @rjmccall! Chances are the compiler I am using will not be changing often.

> With that said, while I can understand being reluctant to bring in an entire C++ standard library as a dependency, both of the major open-source C++ standard library implementations actually have extracted a common sub-library for these ABI routines that you can use independently. I'd be a little surprised if you can't find something that meets your needs between `libsupc++` (GNU) and `libc++abi` (LLVM).

I was not aware that these libraries existed. Unfortunately, I am constrained with which functions I implement due to the fact that the application is safety-critical and therefore any unused functions should not make their way into object code. As much as I would like to use an existing (and trimmed-down) library, it would involve a lot more work to do so in this context.

> > After writing more code, I've had to implement other functions such as __cxa_pure_virtual, __cxa_guard_acquire and __cxa_guard_release because I was receiving an error when compiling saying that these references were undefined. It was clear to me, for these ones, why these functions had to be defined.
> 
> If you're using GCC, you should be able to link with `-lsupc++` (even on bare metal) to get definitions of those. I think you're doing something wrong.

Thanks for the concern, as mentioned before I cannot use such libraries.

Thanks again to both of you for clarifying this for me! It makes more sense now how the compiler might use the __cxa_vec_* functions. I'm inclined to do as @rjmccall suggested and put off writing these definitions until there is a need for them.

**Comment by rjmccall** [comment]
I'm sure those libraries can be configured to build as static archives, and you could do surgery on their build files to make a custom `.a` with only the code that you've personally approved.  But if you're satisfied with writing the code yourself, that's fine, too.

**Comment by jwakely** [comment]
GCC's `libsupc++.a` is *only* provided as a static library. That's what you should be using with GCC.
