### ISSUE TITLE
Missing HTML encoding in 2.3.1 Data Member Pointers

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [itanium-cxx-abi/cxx-abi#172]
In <https://itanium-cxx-abi.github.io/cxx-abi/abi.html#data-member-pointers>, there is an example with this line of code:

```C++
auto mptr = static_cast<char B3::*>(&D::b);
```

<https://github.com/itanium-cxx-abi/cxx-abi/blob/0bc54beef7e908d0a9588acc470ae803e34f3cb4/abi.html#L758-L771>

But the less-than sign in `<char B3::*>` is not encoded as `&lt;` so the Web browser (Safari in my case) treats this as an unrecognised element and does not display it.

**Comment by rjmccall** [comment]
Mind making a PR?
