### ISSUE TITLE
Question about section 2.9.4

### ISSUE THREAD

**Issue by drcxd** [itanium-cxx-abi/cxx-abi#181]
I do not understand the node at the ending of section 2.9.4:

> Note that this ABI requires elsewhere that a virtual table be emitted for a dynamic type in the object where the first non-inline virtual function member is defined, if any, or everywhere referenced if none. Therefore, an implementation should include at least one non-inline virtual function member and define it in the library, to avoid having user code inadvertently preempt the virtual table. Since the Standard requires a virtual destructor, and it will rarely be called, it is a good candidate for this role.

Especially the first sentence. Is it saying that for a virtual table emitted for a class, it must define a non-inline virtual function? Even if so, I still don't understand this part: "or everywhere referenced if none".

What I get is that to prevent user code from preempting the virtual table of the `type_info` class, the compiler has to define a non-inline virtual function. Then why should the compiler do this? What happesn if user code preempts the virtual table?

Thanks

**Comment by jwakely** [comment]
> Especially the first sentence. Is it saying that for a virtual table emitted for a class, it must define a non-inline virtual function?

No, it's saying that if the class has a non-inline virtual function, then the vtable is emitted in the same object as the definition of that non-inline virtual function (which is called the "key function"). If it has no non-inline virtual functions, then the vtable is emitted "everywhere referenced".

> Even if so, I still don't understand this part: "or everywhere referenced if none".

"none" means "has no non-inline virtual functions".

> the compiler has to define a non-inline virtual function.

No, it's not saying that at all. The user defines the virtual functions. The compiler just selects one of the them as the key function, and emits the vtable in the same object as the definition of the key function.

> Then why should the compiler do this?

It doesn't.

> What happesn if user code preempts the virtual table?

I don't know what that means.

**Comment by jwakely** [comment]
> in the object where the first non-inline virtual function member is defined, if any, or everywhere referenced if none

The "if none" is the corollary of "if any".

If it has **any non-inline virtual functions**, the vtable is emitted with the first one. If it has **none**, the vtable is emitted in all objects that might need it (and then the linker discards the duplicates).

**Comment by rjmccall** [comment]
The wording here is unnecessarily confusing.  It's fine for the ABI to make an educational recommendation to C++ programmers, but it should be explicit about it, and it should avoid using words like "the implementation" which are often understanding as referring to the *C++ implementation*, i.e. the compiler/runtime/stdlib.

Additionally, this note seems to be oddly placed (maybe a consequence of some earlier text movement?).  It would make more sense to put in 2.9.2 except that 2.9.2 should really be folded into 5.2.4.  I'll clean that up as part of fixing the wording.

Let's wordsmith this a bit in this issue.  Suggestion:

```
Recommendation for programmers: if a dynamic class has external linkage, and it is neither templated nor attached to a module, make sure it declares at least one non-inline virtual function to serve as a key function.  The virtual destructor is a good candidate for this unless it is sufficiently simple that it would be advantageous to inline.  Providing a key function allows the implementation to avoid redundantly emitting virtual tables and everything they reference (such as inline virtual functions and RTTI objects) into every translation unit that needs to reference the virtual table.  This redundant emission can be a significant drag on compile times and object-file sizes, and it may lead to less efficient code or other problems if the class is provided by a DSO.
```

**Comment by drcxd** [comment]
@jwakely, thanks for your kind and thorough explanation.

Now I understand that the virtual table will be emitted in the same object where a class defines a non-inline virtual function. If no non-inline virtual function is defined, then virtual tables for such class is emitted in any other object it is referenced.

@rjmccall Thanks for your explanation as well. By comparing your suggestion with the original note, I start understanding the idea behind it.

In general the note is a suggestion to optimize the compiling process by defining non-inline virtual functions to reduce the emitting of duplicate virtula tables.

Since my confusion is already clarified, I assume this issue can be closed. However, I am not sure do you want to leave it open since you still have something in discussion? Anyway, feel free to close it as you like and if there is no further discussion I'll close it later.
