### ISSUE TITLE
Questions About Non-POD Types Data Layout

### ISSUE THREAD

**Issue by drcxd** [itanium-cxx-abi/cxx-abi#182]
Hello, I have been reading about the sections of data layout for non-POD types. I am doing experiments to verify if I understand the ABI correctly. I find an example where I think the result of the experiment is not what the ABI described.
 
First, given the following code:

```
#include <stdio.h>
struct A { };
struct B : virtual A { int b; };
struct C { };
struct D : virtual C { int d; };
struct E : B, D { int e; };

int main() {
    E* pe = new E;
    D* pd = pe;
    C* pc = pe;
    B* pb = pe;
    A* pa = pe;
    printf("%p %p %p %p %p", pe, pb, pa, pd, pc);
    return 0;
}
```

I think `B` is the primary base for `E`, `A` is the primary base for `B`, and `C` is the primary base for `D`. Both `A` and `C` are indirect primary bases for `E`.

When allocating `E`, its primary base `B` is allocated first. Since `A` is the primary base for `B`, it is allocated with B. This behavior is described in 2.4 III:

> Any indirect primary base class E of the current class C, i.e. one that has been chosen as the primary base class of some other base class (direct or indirect, virtual or non-virtual) of C, will be allocated as part of that other base class, and is not allocated here.

This should also be the case for allocating `D` and `C`, since `C` is a primary base for `D`. Thus, I assume, `pe == pb == pa` and `pc == pd` and `pd != pb`. However, the output of the program is:

```
0x15b52b0 0x15b52b0 0x15b52b0 0x15b52c0 0x15b52b0
```

which turns out to be `pe == pb == pa == pc` and `pc != pd`. I think this is not what the ABI has described. I am using the compiler labeled as `x86-64 gcc (trunk)` in compiler explorer (godbolt.org) to do this experiment.

Can you help me clarify this problem? Am I understanding the ABI incorreclty? Or the compiler does not implement the ABI faithfully?

Thanks

**Comment by rjmccall** [comment]
`A` and `C` are not primary base classes because they do not have a v-table pointer.

**Comment by drcxd** [comment]
@rjmccall Thanks a lot. Before I read the Itanium C++ ABI, I assumed the base class placed at offset 0 is the "primary base". This incorrect idea still lingers around, and I made such a fundamental mistake unconsiciously. Thank you for pointing that out.

**Comment by rjmccall** [comment]
No problem, it's an easy mistake to make.
