### ISSUE TITLE
Class objects returned in registers even with non-trivial move constructor

### ISSUE THREAD

**Issue by toby-allsopp** [itanium-cxx-abi/cxx-abi#19]
Commit 05fc2335d620e8576ef6de4439e557897e27a73d added a non-trivial move destructor to the criteria for requiring a temporary when passing by value. Should there be a similar change made to the rules for returning class values?

There is some discussion on https://stackoverflow.com/questions/38043288/does-the-c-standard-guarantee-that-a-function-return-value-has-a-constant-addr, in particular the top answer.

The current wording in the ABI document, section 3.1.4, does not agree with the wording in the C++17 draft, which says (http://eel.is/c++draft/class.temporary#3):

> When an object of class type X is passed to or returned from a function, if each copy constructor, move constructor, and destructor of X is either trivial or deleted, and X has at least one non-deleted copy or move constructor, implementations are permitted to create a temporary object to hold the function parameter or result object. The temporary object is constructed from the function argument or return value, respectively, and the function's parameter or return object is initialized as if by using the non-deleted trivial constructor to copy the temporary (even if that constructor is inaccessible or would not be selected by overload resolution to perform a copy or move of the object). [ Note: This latitude is granted to allow objects of class type to be passed to or returned from functions in registers. — end note ]

**Comment by toby-allsopp** [comment]
Note that clang currently implements the ABI as written, which is bad as it violates the language spec. GCC implements the C++ spec.

**Comment by rjmccall** [comment]
That's clearly an oversight; the conditions should be the same.

**Comment by rjmccall** [comment]
I consider this obvious enough that if you write a patch for it, I'll just merge it.  The rules clearly should not be different.

**Comment by rjmccall** [comment]
Actually, never mind, I'll do it.

**Comment by rjmccall** [comment]
Done in 61f9842.

**Comment by toby-allsopp** [comment]
Beautiful, thanks! Now to prod clang into fixing it on their end.
