### ISSUE TITLE
how does itanium c++ abi deal with freestanding C++?

### ISSUE THREAD

**Issue by trcrsired** [itanium-cxx-abi/cxx-abi#192]
All these runtime functions are too big and unsuitable for freestanding development. Any plan to define how to omit all these functions for compilers for freestanding?

**Comment by rjmccall** [comment]
The C++ ABI doesn't require the use of runtime functions for most language functionality. If you disable exceptions and RTTI and don't use the standard non-placement `operator new` and `operator delete`, your compiler will generally not emit any uses of the runtime, and you can elect not to link it.  Is there something more that you're looking for here?

**Comment by trcrsired** [comment]
> The C++ ABI doesn't require the use of runtime functions for most language functionality. If you disable exceptions and RTTI and don't use the standard non-placement `operator new` and `operator delete`, your compiler will generally not emit any uses of the runtime, and you can elect not to link it. Is there something more that you're looking for here?

There are issues with cxa pure virtual, globals etc. It needs more precise on which part compiler should emit in freestanding

**Comment by rjmccall** [comment]
You're right, I was forgetting about those.

If you'd like to work on proposing a concrete freestanding ABI, I think that would be very welcome.  Just opening an issue here isn't going to get that done, though.  And honestly, most of the work there is probably not going to involve changes to the base ABI, it's just doing the work to make libc++abi or libsupc++ work better as a static library.  For example, I don't think we'd want a C++ compiler to implement thread-safe initialization guards with inline code emission even in a freestanding mode.

**Comment by jwakely** [comment]
libsupc++ is already a static library (it's _only_ a static library, there's no `libsupc++.so`). So when linking with `-lsupc++` you will already only link in the symbols that you actually use.

As well as `-fno-rtti` and `-fno-exceptions` there's also `-fno-threadsafe-statics` which means you don't depend on `__cxa_guard_acquire` etc (but if you use local statics, their initialization is not serialized).

I think `__cxa_pure_virtual` might be the only part you can't disable with a compiler option, and that's trivial to provide yourself if you _really_ don't want to link to any runtime (which is what the JDK does), e.g.

`extern "C" void __cxa_pure_virtual() { __builtin_trap(); }`

**Comment by trcrsired** [comment]
also __cxa_delete_virtual?

BTW, libc++ still does not provide support for freestanding C++. Without a precise definition, I cannot persuade libc++ folks on how to implement it.

**Comment by jwakely** [comment]
The C++ standard has a precise definition, and it includes exceptions and RTTI etc. so by the precise definition, you need the entire ABI runtime. Being able to use a subset of that runtime and avoid unwanted overhead is entirely out of scope for the standard and is a quality of implementation matter. Precise definitions won't help.

**Comment by trcrsired** [comment]
> The C++ standard has a precise definition, and it includes exceptions and RTTI etc. so by the precise definition, you need the entire ABI runtime. Being able to use a subset of that runtime and avoid unwanted overhead is entirely out of scope for the standard and is a quality of implementation matter. Precise definitions won't help.

That is the problem since a lot of environment cannot have exceptions, RTTI and heap.

I work in webassembly and wasm cannot use EH. I also compile C++ to Lua through wasm2lua, those environments cannot use EH.

**Comment by jwakely** [comment]
And that's fine, the standard doesn't say you have to use those. It just says that a conforming freestanding implementation must make them available. If you choose not to use them, that's fine.

Whether an implementation allows you to avoid the overhead of features that you don't use is out of scope for the standard, and IMHO out of scope for the ABI spec too. If an implementation has unwanted overhead, that's something you need to discuss with that implementation.

**Comment by trcrsired** [comment]
> And that's fine, the standard doesn't say you have to use those. It just says that a conforming freestanding implementation must make them available. If you choose not to use them, that's fine.
> 
> Whether an implementation allows you to avoid the overhead of features that you don't use is out of scope for the standard, and IMHO out of scope for the ABI spec too. If an implementation has unwanted overhead, that's something you need to discuss with that implementation.

It is not whether I have to. It is that I cannot do. A lot of environments have all sorts of restrictions. In fact, C++ standard does not even say whether walled garden OS like UWP, Android and IOS as hosted or freestanding either. Clearly these walled garden system that prevents users from running binaries directly are not hosted, but not freestanding either.

**Comment by jwakely** [comment]
I stand by my previous comment.

**Comment by trcrsired** [comment]
> And that's fine, the standard doesn't say you have to use those. It just says that a conforming freestanding implementation must make them available. If you choose not to use them, that's fine.
> 
> Whether an implementation allows you to avoid the overhead of features that you don't use is out of scope for the standard, and IMHO out of scope for the ABI spec too. If an implementation has unwanted overhead, that's something you need to discuss with that implementation.

I don't think so. If the standard and the ABI do not satisfy the material existence, the reality is that It needs to change to conform to reality, not vice versa.

**Comment by trcrsired** [comment]
https://www.youtube.com/live/hQJSr2m8qSY?si=YJ_71XjOiDuuLxvb&t=3711

**Comment by rjmccall** [comment]
Okay, this is not the right place to argue about what should be in the standard.

As the ABI editor, I have no problem with the ABI documenting interoperation rules for freestanding implementations.  If those rules need to differ from the standard ABI, we can document those differences, we can also just generally cover the problem and discuss what the compiler, the runtime library, and users need to do in order to satisfy these constrained use cases.  I'm not volunteering to write those sections, though.

**Comment by ldionne** [comment]
It is correct that libc++abi hasn't made a special effort to allow unused parts of the runtime to be eliminated easily. I don't know what happens (in terms of code size) if you link `libc++abi.a` right now and avoid using many of the runtime features. I don't know if this results in code bloat or if the code gets eliminated.

Either way, that seems like a reasonable QOI property to improve on and I'm certain the community would be open to a RFC explaining what you'd like to achieve and how you plan on doing it.

Like others have said, it doesn't seem to me like this needs to live in a standard document since your goal is not to turn off API features, but merely to make sure that you don't pay for said features if you don't use them. That's a property that is usually best handled as a pure QOI matter.

**Comment by rjmccall** [comment]
Every response to you in this issue has been an attempt to engage productively with the technical questions.  Apparently that wasn't what you wanted.  I'm blocking you from this repository, and I'm closing this issue.  If anyone else finds this issue in the future and is interested in working on specifying a freestanding dialect, please feel free to open a new issue; as I mentioned above, I'm totally open as editor to discussing freestanding implementations in the ABI document.

**Comment by rjmccall** [comment]
(fixing closure metadata)

**Comment by rjmccall** [comment]
(reopening)

**Comment by rjmccall** [comment]
(closing as not planned)
