### ISSUE TITLE
Unclear language about registers preserved over landing pads

### ISSUE THREAD

**Issue by purplesyringa** [itanium-cxx-abi/cxx-abi#194]
Something in the Exception Handling doc is unclear to me.

Suppose the unwinder enters a landing pad, copying the callee-saved registers from the context to the machine state. The landing pad then overwrites a callee-saved register and executes `_Unwind_Resume`. Does unwinding proceed with the new value of the register (as if the context was dropped at entry and created in `_Unwind_Resume`) or the old one (as if the context was reused)?

If unwinding is supposed to retain the old state, how does this work wrt. rethrowing, which necessarily recreates the context? I suppose the expected behavior is that the new state is recaptured at each `_Unwind_Resume`, and both `libgcc` and `libunwind` do it that way, but should that perhaps be solidified in the spec?

On a tangential note, what happens to caller-saved registers? The landing pads are surely allowed to clobber them, but what happens in absence of landing pads? Are they captured at `_Unwind_RaiseException` or left undefined? In other words, what happens if I do `mov rax, rsp; call _Unwind_RaiseException` while specifying in `.eh_frame` that the CFA is stored in `rax`? Should the unwinder save all registers to handle this, not just callee-saved ones, at entry points, or is this UB?

**Comment by rjmccall** [comment]
A function is obliged under the psABI to preserve the callee-save registers upon exit from the function.  That includes the logical instant of unwinding out of the function.  The tools it has for achieving this are (1) the personality function, (2) landing pads, and (3) basic info like CFI, and how it chooses to use those tools is really up to the function.  Typically, personality functions don't touch any CSRs in the unwind context, and landing pads just treat calls to `_Unwind_Resume` or `__cxa_rethrow` like any other call, and so register preservation is done entirely by the CFI making sure that registers are restored if they're ever used by the function.  If a landing pad modified `%rbx` before calling `_Unwind_Resume`, and the CFI covering that call site didn't have any information for restoring `%rbx` to its original value, the function would be in violation of its obligations under the psABI.

There are no similar obligations for caller-saved registers, so they can get arbitrarily clobbered at any step of this process.

**Comment by purplesyringa** [comment]
Thanks! This answers my questions.
