### ISSUE TITLE
abi_tag mangling 

### ISSUE THREAD

**Issue by zygoloid** [itanium-cxx-abi/cxx-abi#23]
@jicama  provided wording for the GNU `abi_tag` attribute's mangling here:

https://github.com/jicama/cxx-abi/commit/69cea3c9caf76cb308e35c66f4516f54973b6412

Implementation of this is necessary for ABI compatibility with GCC >=5's libstdc++, so it seems important for the ABI document to cover it.

(Sorry this isn't just a pull request -- github doesn't support PRs for non-branches, and 69cea3c9caf76cb308e35c66f4516f54973b6412 does not seem to be on a branch.)

**Comment by timsong-cpp** [comment]
> and 69cea3c does not seem to be on a branch.

https://github.com/jicama/cxx-abi/commit/891fa38e80df1ab3025a185b769321fc3623590d, perhaps?

**Comment by rjmccall** [comment]
That at least has been updated for Richard's review comment.  But you at least need to put it on a branch to make a PR; I'll do it.

**Comment by rjmccall** [comment]
I agree that we should take this, though.  I still have reservations about the feature itself, but it's unquestionably now necessary for complete interoperation.

**Comment by rjmccall** [comment]
Merged.
