### ISSUE TITLE
Name mangling for possible new Clang type

### ISSUE THREAD

**Issue by agozillon** [itanium-cxx-abi/cxx-abi#28]
Hello, I put forward a patch for review not that long ago that adds a new type to Clang. It's a dependent type that I use to enable template parameters in conjunction with address spaces. The patch itself and further details can be viewed here: https://reviews.llvm.org/D33666 

In essence, as it's a new type if it was to be accepted it would need an appropriate name mangling. So I was hoping to raise a discussion on a name mangling if that's possible. At the moment the mangling function is as follows:   

void CXXNameMangler::mangleType(const DependentExtAddressSpaceType *T) {
  Out << "DEas";
  mangleExpression(T->getAddrSpaceExpr());
  Out << '_';
  mangleType(T->getPointeeType());
}

I'm quite unaware of the naming conventions used, so I doubt it's ideal at the moment. I followed suit from the existing DependentSizedExtVectorType mangling function. Which does something quite similar with its size expr and element type. In this case the AddrSpace expression would be the address space index. The PointeeType would be the type the address space is to be attached to when it's no longer dependent. The DEas acronym is the types name minus the Type section of the name. 

Thank you very much for your time and consideration on this issue, I apologies if this is the incorrect way to raise this type of issue and would appreciate redirection to the appropriate avenue if that is the case.

**Comment by jicama** [comment]
Could you use a vendor extendend type qualifier to attach the address space
to the template parameter?

**Comment by rjmccall** [comment]
The current vendor-extended type qualifier for address spaces makes the literal address space part of the <source-name>, e.g. "U4AS16".   I believe that predated proper support for parameterized qualifiers; if we were doing it now, it would probably be "U2ASILi16EE", and that's probably the right pattern to use here.

**Comment by rjmccall** [comment]
That is, this should just be "U2ASI" <expression> "E".

We should probably document the mangling of the address_space qualifier, since it doesn't follow the standard rule of using the qualifier's source spelling.

**Comment by agozillon** [comment]
If I am following this correctly then would the mangling function change to the following:

void CXXNameMangler::mangleType(const DependentExtAddressSpaceType *T) {
Out << "U2ASI";
mangleExpression(T->getAddrSpaceExpr());
Out << 'E';
}

**Comment by rjmccall** [comment]
Yes, except you need to respect the correct ordering of qualifiers, and you may need to worry about qualifier nesting, i.e. whether you have `Const(DependentExtAddressSpace(int))` vs. `DependentExtAddressSpace(Const(int))`.  Please take further discussion of that back to the Clang development lists, however.

**Comment by rjmccall** [comment]
@jicama How does GCC mangle address_space?  I don't seem to have a copy of GCC for a port that supports a non-generic address space.

**Comment by jicama** [comment]
The C++ front end doesn't support named address spaces yet.

Jason

**Comment by thiagomacieira** [comment]
FWIW, that's https://gcc.gnu.org/bugzilla/show_bug.cgi?id=69549.

**Comment by rjmccall** [comment]
Okay.  Do you have any objection to adopting our mangling if you ever decide to implement them?  If not, I'll prepare a PR for that.

**Comment by jicama** [comment]
No objection, the mangling looks fine.

**Comment by rjmccall** [comment]
I've submitted a pull request (#29) documenting the address_space mangling.

**Comment by rjmccall** [comment]
Merged that PR, which I believe finishes this issue.
