### ISSUE TITLE
error in abi-examples.html Table 1b: Example Data Layout 

### ISSUE THREAD

**Issue by blacktrain** [itanium-cxx-abi/cxx-abi#32]
struct X {
  int ix;
  virtual void x();
};
struct E : X, D { 
  void f (); 
  void h ();  
  int ie;  
};

sizeof(E) should be 72,not 64

**Comment by zygoloid** [comment]
I assume you mean cxx-vtable-ex.html?

**Comment by zygoloid** [comment]
Also the listing of members is wrong -- `ie` is omitted.

**Comment by blacktrain** [comment]
yeah,I meaning cxx-vtable-ex.html,sorry about my carelessness。
