### ISSUE TITLE
reserve manglings containing a period for vendor-specific versions / pieces of functions?

### ISSUE THREAD

**Issue by zygoloid** [itanium-cxx-abi/cxx-abi#35]
Several vendors use mangled names of the form

  real_mangled_name.suffix

to represent either a version of a function (eg, parameter 3 is the constant x) or a piece of a function (eg, coroutine resumption slice of a function) or similar. However, demanglers are inconsistent in their handling of this form -- some require the suffix to contain only digits, others support and ignore an arbitrary suffix, others simply reject all such names as being an invalid mangling.

We should officially permit such manglings for internal-linkage symbols, with an arbitrary suffix, in order to give clear guidance to demangler implementers.

**Comment by rjmccall** [comment]
Seems like a good idea.
