### ISSUE TITLE
operator encoding for spaceship operator

### ISSUE THREAD

**Issue by zygoloid** [itanium-cxx-abi/cxx-abi#43]
[P0515](http://wg21.link/p0515), voted into the C++20 working draft, adds a new operator token `<=>`, which needs a mangling. This is formally called the "three-way comparison operator", but informally called the "spaceship operator".

I suggest we mangle `<=>` as `ss`.

**Comment by rjmccall** [comment]
That seems like a reasonable proposal; mind writing a PR?

**Comment by rjmccall** [comment]
What do you think — should we leave this open until the draft is finalized?

**Comment by zygoloid** [comment]
Multiple implementations are going to ship this for the intervening ~two years (and want ABI stability when the standard draft is finalized), so my preference would be to add it to the ABI document now. But having it here in the issues list and clearly our plan of record seems like a reasonable alternative if you'd rather not document manglings for things that are not yet standardized.

**Comment by rjmccall** [comment]
No, I have no strong feelings against accepting something that seems very clearly destined for standardization.
