### ISSUE TITLE
mangling for char8_t

### ISSUE THREAD

**Issue by tahonermann** [itanium-cxx-abi/cxx-abi#45]
I'm working on adding prototype support for [P0482](http://wg21.link/p0482) to gcc and am interested in reserving a mangling for the `char8_t` type.

`char16_t` and `char32_t` use `Ds` and `Di` respectively.  `s` and `i` correspond to `short` and `int`.  `Dc` (`c` for `char`) or `Dh` (`h` for `unsigned char`) would be the obvious candidates, but both are taken (for `decltype(auto)` and IEEE 754 support respectively).  I believe `Du` is currently available, so I'll suggest that as a starting point.

For now, I'm using the vendor extended type mangling (`u7char8_t`) and am fine with that at least until support for `char8_t` is accepted in upstream gcc.

**Comment by zygoloid** [comment]
I just started thinking about this for a Clang implementation and independently arrived at `Du` being the best choice.

**Comment by skochinsky** [comment]
Looks likg GCC now uses `Du` as well? https://github.com/gcc-mirror/gcc/commit/82362779f2ccfba6c9780079bf5e28a6d5b8fe25

**Comment by tahonermann** [comment]
> Looks like GCC now uses Du officially? gcc-mirror/gcc@8236277

Correct.  I stopped using the vendor extended type mangling before submitting the changes for inclusion in gcc 9.

**Comment by j04n** [comment]
Shouldn't "Du" mangling be officially mentioned in ABI docs by now? 

(Might not be the right place to ask, sorry!)

I saw it used in many binaries out there, and had a hard time finding a proper definition, until this thread.

**Comment by tahonermann** [comment]
> Shouldn't "Du" mangling be officially mentioned in ABI docs by now?

Yes, but no one submitted a PR to actually get the docs updated.  I have now.

**Comment by rjmccall** [comment]
Thanks for writing that up.
