### ISSUE TITLE
The type of an 'auto' lambda parameter should be mangled as the corresponding template type parameter

### ISSUE THREAD

**Issue by urnathan** [itanium-cxx-abi/cxx-abi#8]
The document isn't clear that 'auto' in a generic lambda should be mangled as the underlying artificial template type parm.  doing that can lead to recursive manglings (which is one reason why I thought it a bug).

Here's a suggested diff (sorry, had to gzip it to attach it)

[abi-lambda.diff.gz](https://github.com/itanium-cxx-abi/cxx-abi/files/705154/abi-lambda.diff.gz)

**Comment by rjmccall** [comment]
If you've already got that as a diff, can you just make it a pull request?

**Comment by rjmccall** [comment]
This was merged awhile back, closing.
