### ISSUE TITLE
module-scope lambda closure types will need mangling

### ISSUE THREAD

**Issue by zygoloid** [itanium-cxx-abi/cxx-abi#84]
Consider:

```
export module M;
export int *f(decltype([]{T t;}) lambda) {
  static int n;
  return &n;
}
export int *g() { return f(); }
export int *f(decltype([]{T t;}) lambda) {
  static int n;
  return &n;
}
```

(The function parameters have different types, so we have two overloaded `f` functions rather than a redefinition error.)

If this module is imported into multiple translation units, they must agree on the type of the function parameter; calling `g()` in those translation units must return the same static variable.

Similarly:

```
export module M;
using T = decltype([]{});
```

... must use the same type for `lambda` in every translation unit in which `M` is imported, so we need some linkage name for that closure type.

Proposal: number all lambdas appearing outside of any other numbering context in an importable translation unit (module interface unit, partition, or header unit) lexically within the translation unit. Restart the numbering (with some suitable disambiguator) at the module declaration in order to try to make the numbering as stable as possible.

**Comment by rjmccall** [comment]
The call in `g` is ill-formed, but it's simple to make it well-formed, so I agree this is an issue.

I also agree that I don't see a solution besides some sort of global counter.

**Comment by opensdh** [comment]
@zygoloid: I think this issue _and_ the corresponding part of #34 may be resolved by P1815R2, as we [rediscovered on the reflector](https://lists.isocpp.org/core/2020/04/8836.php).

**Comment by zygoloid** [comment]
I believe this issue can be closed, per @opensdh's comment. [\[basic.link\]/15.2](https://eel.is/c++draft/basic.link#15.2) says that lambda-expression closure types, and things declared within them, are TU-local unless they appear in function bodies, classes, or initializers, and it's ill-formed for a TU-local entity to be "exposed" from a module (including by simply being mentioned from within an inline function or function template). So there is no need to mangle arbitrary lambdas appearing in a module unit.
